//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competitor()
        {
            this.CompetitorEventRelations = new HashSet<CompetitorEventRelation>();
            this.DivisionGroups = new HashSet<DivisionGroup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string School { get; set; }
        public string Belt { get; set; }
        public string Event { get; set; }
        public string RegistrationDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Path { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string ProfilePath { get; set; }
        public string CoachName { get; set; }
        public Nullable<bool> IsCheckin { get; set; }
        public string Remarks { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitorEventRelation> CompetitorEventRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionGroup> DivisionGroups { get; set; }
    }
}
