//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorTournamentOrder
    {
        public int Id { get; set; }
        public string Competitor { get; set; }
        public string Tournament { get; set; }
        public string Event { get; set; }
        public string Division { get; set; }
        public int SortOrder { get; set; }
    }
}
