//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyRepo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourneyWizardEntities : DbContext
    {
        public TourneyWizardEntities()
            : base("name=TourneyWizardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AnnualOffDay> AnnualOffDays { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Belt> Belts { get; set; }
        public virtual DbSet<Competitor> Competitors { get; set; }
        public virtual DbSet<CompetitorEventRelation> CompetitorEventRelations { get; set; }
        public virtual DbSet<CompetitorTournamentOrder> CompetitorTournamentOrders { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<DivisionGroup> DivisionGroups { get; set; }
        public virtual DbSet<EventDivision> EventDivisions { get; set; }
        public virtual DbSet<QRCodeDetail> QRCodeDetails { get; set; }
        public virtual DbSet<ScheduledEvent> ScheduledEvents { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TournamentDirector> TournamentDirectors { get; set; }
        public virtual DbSet<TournamentEvent> TournamentEvents { get; set; }
        public virtual DbSet<TournamentEventRealtion> TournamentEventRealtions { get; set; }
    }
}
